---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop: 
    - gpg
    - wget

- name: get key
  shell: "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg"

- name: install key
  shell: "sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/"

- name: get repo
  shell: "sudo sh -c 'echo \"deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main\" > /etc/apt/sources.list.d/vscode.list'"

- name: install key
  shell: "sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/"

- name: remove microsoft gpg
  shell: "rm -f packages.microsoft.gpg"

- name: install apt dependency
  shell: "sudo apt install apt-transport-https"

- name: apt update
  shell: "sudo apt update"

- name: install vscode
  shell: "sudo apt install code"

# - name: add vscode apt key
#   apt_key:
#     url: "{{ vscode_apt_key }}"

# - name: add vscode repo
#   apt_repository:
#     repo: "{{ vscode_repo }}"
#     state: present
#     filename: code

# - name: install latest visual studio code
#   apt:
#     name: "{{item}}"
#     update_cache: yes
#     state: latest
#   loop:
#     - code


# - name: install vscode deb package
#   shell: "sudo apt install code"



# - name: install some popular vscode extensions
#   command: code --install-extension {{ item }}
#   with_items: "{{ vscode_extensions }}"
#   become: yes
#   become_user: "{{ local_username }}"


...
