---

# mount /tmp on tmpfs
- block:
    - name: clear the existing /tmp dir (1/5)
      shell: "/bin/rm -rf *"
      args:
        chdir: /tmp
        warn: no

    - name: copy systemd file (2/5)
      copy:
        src: /usr/share/systemd/tmp.mount
        dest: /lib/systemd/system/tmp.mount
        remote_src: True

    - name: create dir /etc/systemd/system/tmp.mount.d (3/5)
      file:
        path: /etc/systemd/system/tmp.mount.d
        state: directory

    - name: create tmp.mount custom options file (4/5)
      copy:
        dest: /etc/systemd/system/tmp.mount.d/options.conf
        content: |
          [Mount]
          Options=mode=1777,strictatime,nosuid,nodev,size=512M

    - name: start and enable tmp.mount on boot (5/5)
      systemd:
        name: tmp.mount
        enabled: yes
        state: started
        daemon_reload: yes

# remove Satan's bastard child snap (and snap packages)
- block:
    - name: remove snapd (1/3)
      apt:
        name: snapd
        state: absent
        autoremove: yes
        purge: yes

    - name: restrict snapd package from being installed (2/3)
      copy:
        dest: /etc/apt/preferences.d/nosnap.pref
        src: etc/apt/preferences.d/nosnap.pref
        owner: root
        group: root
        mode: '0644'

    - name: install firefox deb package which was a snap package (3/3)
      apt:
        name: firefox
        update_cache: yes
        force_apt_get: yes
  when: remove_snapd

- name: enable ufw firewall
  ufw:
    state: enabled

- name: disable system crash reports
  lineinfile:
    dest: /etc/default/apport
    regexp: "^enabled=(0|1)"
    line: enabled=0
    state: present

# It may be desirable to set this to zero, so that application memory is retained as long as possible at the expense
# of the page cache. When there is still a memory shortage, the kernel can still use swapping.
- name: tune system swappiness
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: reduce space used by journald
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse=$'
    line: SystemMaxUse=256M

- name: perform a dist upgrade
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes

- name: install archiving tools
  apt:
    name: "{{ base_archiving_tools }}"
    state: present
    force_apt_get: yes

- name: install productivity tools
  apt:
    name: "{{ base_productivity_tools }}"
    state: present
    force_apt_get: yes

- name: install system tools
  apt:
    name: "{{ base_system_tools }}"
    state: present
    force_apt_get: yes

- name: install system tools for laptop
  apt:
    name: "{{ base_system_tools_laptop }}"
    state: present
    force_apt_get: yes
  when: laptop_mode

- name: install developer tools
  apt:
    name: "{{ base_developer_tools }}"
    state: present
    force_apt_get: yes

# Fix for bat syntax highlighting tool; Ubuntu packages it as batcat instead of just bat
- name: create symlink for bat
  file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    state: link
    force: no

- name: set nc to point to nmap's netcat implementation
  alternatives:
    name: nc
    path: /usr/bin/ncat

- name: create .ssh dir
  file:
    path: "~{{ local_username }}/.ssh"
    state: directory
    mode: '0700'
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: Create directories for golang
      file:
        path: "~{{ local_username }}/{{ item }}"
        state: directory
      with_items:
        - go
        - go/src
        - go/bin

    - name: Make GOPATH available in .bashrc
      lineinfile:
        path: "~{{ local_username }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - export GOPATH=$HOME/go
        - export PATH=$PATH:$GOPATH/bin
  become: yes
  become_user: "{{ local_username }}"

- name: install download tools
  apt:
    name: "{{ base_download_tools }}"
    state: present
    force_apt_get: yes

- name: install media packages
  apt:
    name: "{{ base_media_tools }}"
    state: present
    force_apt_get: yes

# - name: install virtualization tools
#   apt:
#     name: "{{ base_virtualization_tools }}"
#     state: present
#     force_apt_get: yes

# add user to docker group to run docker commands without sudo
# add user to vboxusers group so that user can attach usb devices to guest OS

#- name: install virtualbox extensions pack
#  shell: echo 'y' | vboxmanage extpack install --replace /usr/share/virtualbox-ext-pack/Oracle*

- name: Enable permanent night light settings
  command: "gsettings set org.gnome.settings-daemon.plugins.color {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'night-light-enabled', value: "{{ base_permanent_night_light.night_light_enabled | string | lower }}" }
    - { key: 'night-light-schedule-automatic', value: "{{ base_permanent_night_light.night_light_schedule_automatic | string | lower }}" }
    - { key: 'night-light-schedule-from', value: "{{ base_permanent_night_light.night_light_schedule_from }}" }
    - { key: 'night-light-schedule-to', value: "{{ base_permanent_night_light.night_light_schedule_to }}" }
    - { key: 'night-light-temperature', value: "{{ base_permanent_night_light.night_light_temperature }}" }

  when: base_permanent_night_light.night_light_enabled
  become_user: "{{ local_username }}"

# make fstrim run daily rather than the default weekly schedule for SSD longevity
- block:
    - name: enable fstrim.timer
      systemd:
        name: fstrim.timer
        state: started
        enabled: yes

    - name: create systemd fstrim.timer override dir
      file:
        path: /etc/systemd/system/fstrim.timer.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: create override.conf file for fstrim.timer
      copy:
        src: etc/systemd/system/fstrim.timer.d/override.conf
        dest: /etc/systemd/system/fstrim.timer.d/override.conf
        owner: root
        group: root
        mode: 0644

    - name: force systemd to reread configs
      systemd:
        daemon_reload: yes

...
